/*
 * Copyright 2026 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.test.api.scalatest.tags

import org.scalatest.Tag

// Auto-generated by TagsObjectGenerator. Re-run after spec tags change.

object DTD_417 extends Tag("DTD_417")
object DTD_1874 extends Tag("DTD_1874")
object DTD_1959 extends Tag("DTD_1959")
object DTD_3003 extends Tag("DTD_3003")
object DTD_2140 extends Tag("DTD_2140")
object DTD_2166 extends Tag("DTD_2166")
object DTD_2167 extends Tag("DTD_2167")
object DTD_2168 extends Tag("DTD_2168")
object DTD_2216 extends Tag("DTD_2216")
object DTD_2243 extends Tag("DTD_2243")
object DTD_2244 extends Tag("DTD_2244")
object DTD_2273 extends Tag("DTD_2273")
object DTD_2274 extends Tag("DTD_2274")
object DTD_2351 extends Tag("DTD_2351")
object DTD_2371 extends Tag("DTD_2371")
object DTD_2714 extends Tag("DTD_2714")
object DTD_2790  extends Tag("DTD_2790")
object DTD_2940 extends Tag("DTD_2940")
object DTD_3163 extends Tag("DTD_3163")
object DTD_3180 extends Tag("DTD_3180")
object DTD_3325 extends Tag("DTD_3325")
object DTD_3523 extends Tag("DTD_3523")
object DTD_400 extends Tag("DTD_400")
object DTD_4201 extends Tag("DTD_4201")
object DTD_1730 extends Tag("DTD_1730")
object WIP extends Tag("WIP")
object suppression extends Tag("suppression")
